server:
  BindAddress: http://0.0.0.0:8080
upstreamConfig:
  upstreams:
    - id: foo
      path: /
      uri: http://localhost:8181
providers:
  - id: dummy
    name: dummy
    clientId: CLIENT_ID
    clientSecret: CLIENT_SECRET
    provider: google
